#!/bin/bash
# Read /etc/passwd, /etc/shadow, and /etc/group
users=$(awk -F: '$3 >= 3000 && $3 <= 3099 {print $0}' /etc/passwd)
shadows=$(awk -F: '$3 >= 3000 {print $0}' /etc/shadow)
groups=$(awk -F: '$3 >= 3000 && $3 <= 3099 {print $0}' /etc/group)

# Create the Ansible playbook file
playbook_file="dmusers.yaml"
echo "---" > "$playbook_file"
echo "- name: Clone DM users" >> "$playbook_file"
echo "  hosts: saclass" >> "$playbook_file"
echo "  become: true" >> "$playbook_file"
echo "  remote_user: owbi7083" >> "$playbook_file"
echo "  tasks:" >> "$playbook_file"
# Loop through each user
while IFS=: read -r user; do
    username=$(echo "$user" | cut -d: -f1)
    uid=$(echo "$user" | cut -d: -f3)
    gecos=$(echo "$user" | cut -d: -f5)
    shell=$(echo "$user" | cut -d: -f7)

    # Find the corresponding shadow entry
    shadow=$(echo "$shadows" | grep "^$username:")

    # Find the groups for the user
    user_groups=$(echo "$groups" | awk -F: -v username="$username" '$4 ~ username {print $1}')

    # Assign users to the correct groups
    if [[ "$username" == "abernard" || "$username" == "plapin" || "$username" == "shudson" ]]; then
        user_groups+=" 'sales'"
    fi
    if [[ "$username" == "mscott" || "$username" == "jhalpert" || "$username" == "dschrute" ]]; then
        user_groups+=" 'managers'"
    fi
    if [[ "$username" == "amartin" || "$username" == "omartinez" || "$username" == "kmalone" ]]; then
        user_groups+=" 'accounting'"
    fi

    # If me && in wheel group, add sudoers, sudo, and wheel groups on all other machines
    if [[ "$username" == "owbi7083" ]]; then
        if grep -q "^wheel:" /etc/group; then
                user_groups+=" sudoers, sudo, wheel"
        fi
    fi

    # Write user blocks
    echo "  - name: Set parameters for user $username" >> "$playbook_file"
    if [[ "$username" == "owbi7083" ]]; then
        echo "    ignore_errors: true" >> "$playbook_file"
    fi
    

    
    echo "    user:" >> "$playbook_file"
    echo "      name: $username" >> "$playbook_file"
    echo "      uid: $uid" >> "$playbook_file"
    if [[ -n "$gecos" ]]; then
        echo "      gecos: $gecos" >> "$playbook_file"
    fi
    echo "      shell: $shell" >> "$playbook_file"
    echo "      home: /home/$username" >> "$playbook_file" # Add home directory
    echo "      createhome: true" >> "$playbook_file" # Create home directory if it doesn't exist
    echo "      skeleton: /etc/skel" >> "$playbook_file" # Use /etc/skel as the skeleton directory
    if [[ -n "$user_groups" ]]; then
        groups=$(echo "$user_groups" | tr '\n' ',')
        groups=${groups%,}  # Remove trailing comma
        echo "      groups:$groups" >> "$playbook_file"
    fi
    echo "      password: $(echo "$shadow" | cut -d: -f2)" >> "$playbook_file"
    echo "" >> "$playbook_file" # New line
    echo >> "$playbook_file"
    chown owbi7083:owbi7083 "$playbook_file" # Own file so it can be run without sudo
    done <<< "$users"