#!/bin/bash

count=3000
username=("mscott" "jhalpert" "dschrute" "pbeesly" "abernard" "plapin" "shudson" "amartin" "omartinez" "kmalone" "dphilbin" "kkapoor" "tflenderson" "mpalmer" "cbratton" "owbi7083")
#name=("Michael Scott" "Jim Halpert" "Dwight Schrute" "Pam Beesly" "Andy Bernard" "Phyllis Lapin" "Stanley Hudson" "Angela Martin" "Oscar Martinez" "Kevin Malone" "Darryl Philbin" "Kelly Kapoor" "Toby Flenderson" "Meredith Palmer" "Creed Bratton" "Owen Billings")
title=("Regional Manager" "Assistant Regional Manager" "Assistant to the Regional Manager" "Receptionist" "Regional Director in Charge of Sales" "Sales Representative" "Sales Representative" "Senior Accountant" "Accountant" "Accountant" "Warehouse Foreman" "Customer Service Representative" "Human Resources" "Supplier Relations" "Quality Assurance Representative" "System Administrator")


echo "#!/bin/bash" > "/etc/profile.d/umask.sh"
echo "umask 077" >> "/etc/profile.d/umask.sh"
chmod +x "/etc/profile.d/umask.sh"
sudo mkdir -p /etc/skel/etc/skel



groupadd managers
groupadd sales
groupadd accounting


for i in "${!username[@]}"; do
    useradd -mU --shell "/bin/bash" --uid $count -b "/home" "${username[$i]}"
    echo "${username[$i]}:goat1604" | chpasswd

    if [[ "${title[$i]}" == *"Manager"* ]]; then
        usermod -aG managers "${username[$i]}"
    elif [[ "${title[$i]}" == *"Sales"* ]]; then
        usermod -aG sales "${username[$i]}"
    elif [[ "${title[$i]}" == *"Accountant"* ]]; then
        usermod -aG accounting "${username[$i]}"
    fi
    count=$((count+1))
done
usermod -aG sudo "owbi7083"
usermod -aG wheel "owbi7083"